# fetch the artiacts from the previous job
# install frontend deps
# build frontend

name: build-frontend

on:
  push:
    branches:
      - github_build

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
            
      - name: Download JSON Bundle
        uses: actions/download-artifact@v3
        with:
          name: dist-json-bundle
          path: ./frontend/public/data/

      - name: Use Node.js 18.15.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - run: npm ci
      - run: npm run build
      
### CDK Stuff


      # - name: create-json
      #   id: create-json
      #   uses: jsdaniell/create-json@v1.2.2
      #   working-directory: ./cdk
      #   with:
      #     name: "config.json"
      #     json: ${{ secrets.DEV_CONFIG }}

      # - name: cdk diff
      #   uses: youyo/aws-cdk-github-actions@v2
      #   working-directory: ./cdk
      #   with:
      #     cdk_subcommand: 'diff'
      #     actions_comment: true
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: cdk deploy
      #   uses: youyo/aws-cdk-github-actions@v2
      #   working-directory: ./cdk
      #   with:
      #     cdk_subcommand: 'deploy'
      #     cdk_stack: 'stack1'
      #     cdk_args: '--require-approval never'
      #     actions_comment: false
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: cdk synth
      #   uses: youyo/aws-cdk-github-actions@v2
      #   working-directory: ./cdk
      #   with:
      #     cdk_subcommand: 'synth'
      #     cdk_version: '1.16.2'
      #     working_dir: 'src'
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
