# download the json files from the generate_jsons job
# install npm dependencies
# build the frontend
# store the frontend bundle as artifact

name: build-frontend

on:
  push:
    branches:
      - github_build

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [generate_jsons]

    steps:

      # download the artifacts from the generate_jsons job
      - name: Download the JSON Bundle
        uses: actions/download-artifact@v2
        with:
          name: dist-json-bundle
          path: ./frontend/public/data/



      # bundle the frontend
      - name: Use Node.js 18.15.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - run: npm ci
        working-directory: ./frontend
      - run: npm run build
        working-directory: ./frontend

      # store the frontend bundle as artifact
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-frontend-bundle
          path: |
            ./frontend/dist/
