name: check-style

on:
  push:

jobs:
  check_crawler_style:
    runs-on: ubuntu-latest

    # run when crawler changes
    if: ${{ contains(github.event.head_commit.modified, 'crawler/') }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      # Install + Cache Crawler Dependencies
      - name: Cache Node Modules | Crawler
        id: cache-crawler-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-crawler-npm
        with:
          path: ${{ github.workspace }}/crawler/node_modules/
          key: cache-crawler-yarn-${{ hashFiles('crawler/yarn.lock') }}

      - name: Install Node Modules | Crawler
        if: steps.cache-crawler-npm.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        working-directory: ${{ github.workspace }}/crawler

      - name: Check Style | Crawler
        run: yarn format
        working-directory: ${{ github.workspace }}/crawler/

  # check_frontend_style:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - uses: actions/checkout@v3

  #     - name: Use Node.js 22.12.0
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 22.12.0

  #     - name: Cache NPM Modules
  #       id: cache-frontend-npm
  #       uses: actions/cache@v3
  #       env:
  #         cache-name: cache-frontend-npm
  #       with:
  #         path: ./frontend/node_modules/
  #         key: cache-frontend-npm-${{ hashFiles('frontend/package-lock.json') }}

  #     - name: Install Dependencies
  #       if: steps.cache-frontend-npm.outputs.cache-hit != 'true'
  #       run: npm ci
  #       working-directory: ./frontend

  #     - name: Check Frontend Style
  #       working-directory: ${{ github.workspace }}/frontend/
  #       run: yarn format

  # - name: Check Crawler Style
  #   uses: creyD/prettier_action@v4.3
  #   with:
  #     working_directory: ${{ github.workspace }}/crawler/
  #     dry: true
  #     github_token: ${{ github.token }}
  #     prettier_options: --check ./src/**/*.js
