name: check-style

on:
  push:
    branches:
      - check_style

jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check Frontend Style
        uses: creyD/prettier_action@v4.3
        with:
          working_directory: frontend/
          dry: True
          github_token: ${{ github.token }}
          prettier_options: --check ./src/**/*.{jsx,js}

      - name: Check Crawler Style
        uses: creyD/prettier_action@v4.3
        with:
          working_directory: crawler/
          dry: True
          github_token: ${{ github.token }}
          prettier_options: --check ./src/**/*.js
