name: check-style

on:
  push:
    branches:
      - check_style

jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   # Make sure the actual branch is checked out when running on pull requests
        #   ref: ${{ github.head_ref }}
      - name: Check Frontend Style
        uses: creyD/prettier_action@v4.3
        with:
          working_directory: ${{ github.workspace }}/frontend/
          dry: true
          github_token: ${{ github.token }}
          prettier_options: --check ./src/**/*.{jsx,js}

      - name: Check Crawler Style
        uses: creyD/prettier_action@v4.3
        with:
          working_directory: ${{ github.workspace }}/crawler/
          dry: true
          github_token: ${{ github.token }}
          prettier_options: --check ./src/**/*.js
